apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-service
  template:
    metadata:
      labels:
        app: feedback-service
    spec:
      containers:
      - name: feedback-service
        image: yashwanthydg/feedback-service:v2 # <-- IMPORTANT: Change this
        ports:
        - containerPort: 8002
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: feedback-service
spec:
  type: ClusterIP # Only accessible within the cluster
  selector:
    app: feedback-service
  ports:
  - port: 8002
    targetPort: 8002
