name: CI/CD for Feedback Service

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: feedback-service
  K8S_DEPLOYMENT_NAME: feedback-service

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/feedback-service:${{ github.sha }}

  deploy:
    name: Deploy to Kubernetes
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/feedback-service=${{ secrets.DOCKERHUB_USERNAME }}/feedback-service:${{ github.sha }}
          echo "Deployment updated successfully!"
